apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "nexvion.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: nexvion

  template:
    metadata:
      labels:
        app: nexvion

    spec:
      containers:
        - name: nexvion

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: {{ include "nexvion.fullname" . }}-config
            - secretRef:
                name: {{ include "nexvion.fullname" . }}-secret

          ports:
            - containerPort: {{ .Values.service.targetPort }}
