input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => {
      "application" => "Nexvion"
      "environment" => "production"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "nexvion-logs"
  }

  stdout {
    codec => rubydebug
  }
}
